# Hungarian translations for each key
$huTranslations = @{
    'tx_receipt' = 'Tranzakció Visszaigazolás'
    'tx_failed' = 'Sikertelen Tranzakció'
    'tx_pending' = 'Függő Tranzakció'
    'tx_on_hold' = 'Visszatartott Tranzakció'
    'tx_processing' = 'Tranzakció Feldolgozás Alatt'
    'payment_successful' = 'Sikeres Fizetés'
    'payment_failed' = 'Sikertelen Fizetés'
    'payment_pending' = 'Függő Fizetés'
    'tx_desc_success' = 'Tranzakciója sikeresen feldolgozásra került.'
    'tx_desc_failed' = 'Tranzakcióját nem sikerült feldolgozni. Kérjük, lépjen kapcsolatba az ügyfélszolgálattal.'
    'tx_desc_pending' = 'Tranzakciója jelenleg jóváhagyásra vár.'
    'tx_desc_onhold' = 'Tranzakciója visszatartásra került. Kérjük, lépjen kapcsolatba az ügyfélszolgálattal további információkért.'
    'tx_desc_processing' = 'Tranzakciója jelenleg feldolgozás alatt áll.'
    'recipient' = 'Címzett'
    'date' = 'Dátum'
    'reference_id' = 'Hivatkozási szám'
    'status' = 'Állapot'
    'usd_amount' = 'USD összeg'
    'view_details' = 'Részletek megtekintése'
    'questions_ref_id' = 'Ha kérdése van, kérjük, hivatkozzon a hivatkozási számra.'
    'support_replied' = 'Az Ügyfélszálat Válaszolt'
    'support_replied_desc' = 'Ügyfélszolgálati csapatunk válaszolt az élő chat üzenetére.'
    'latest_reply' = 'Legutóbbi Válasz'
    'view_reply_continue' = 'Válasz Megtekintése és Chat Folytatása'
    'need_help' = 'Segítségre van szüksége?'
    'continue_live_chat' = 'Élő chat folytatása'
    'button_doesnt_work' = 'Ha a gomb nem működik, másolja ki és illessze be ezt a linket:'
    'hello_there' = 'Üdvözlöm'
    'amount' = 'Összeg'
    'fee' = 'Díj'
    'total' = 'Összesen'
    'subtotal' = 'Részösszeg'
    'transaction_id' = 'Tranzakció azonosító'
    'transaction_date' = 'Tranzakció dátuma'
    'sender' = 'Feladó'
    'sender_name' = 'Feladó neve'
    'recipient_name' = 'Címzett neve'
    'recipient_email' = 'Címzett e-mail'
    'recipient_account' = 'Címzett számla'
    'incoming_deposit_notification' = 'Bejövő Közvetlen Befizetés Értesítés'
    'direct_deposit_confirmation' = 'Közvetlen Befizetés Megerősítése'
    'dear' = 'Tisztelt'
    'hi' = 'Szia'
    'valued_customer' = 'Értékes Ügyfelünk'
    'deposit_intro' = 'Értesítjük, hogy egy közvetlen befizetés érkezett és jóváírásra került számláján. Kérjük, tekintse át a tranzakció részleteit alább.'
    'deposit_intro_peoplechoice' = 'Örömmel értesítjük, hogy egy közvetlen befizetés jóváírásra került számláján. További teendő nincs, hacsak nem észlel eltérést.'
    'transaction_details' = 'Tranzakció Részletei'
    'action_required' = 'Intézkedés Szükséges'
    'confirm_receipt_deposit' = 'Kérjük, erősítse meg a befizetés átvételét a tranzakciós nyilvántartás teljesítéséhez.'
    'confirm_payment' = 'Fizetés Megerősítése'
    'confirm_deposit' = 'Befizetés Megerősítése'
    'security_notice' = 'Biztonsági Értesítés'
    'security_notice_text' = 'A {bank} soha nem kéri el jelszavát, PIN-kódját vagy teljes kártyaszámát e-mailben. Ha nem várt ezt a befizetést, kérjük, azonnal lépjen kapcsolatba Csalásmegelőzési csapatunkkal a támogatási csevegésen keresztül.'
    'automated_notification' = 'Ez egy automatikus értesítés a {bank} rendszeréből. Kérjük, ne válaszoljon erre az e-mailre.'
    'all_rights_reserved' = 'Minden jog fenntartva'
    'member_fdic' = 'FDIC tag'
    'equal_housing_lender' = 'Egyenlő Lakhatási Hitelező'
    'member_kdic' = 'KDIC tag'
    'time' = 'Idő'
    'confirm_accept_deposit' = 'Befizetés Megerősítése és Elfogadása'
    'track_transfers_anytime' = 'Kövesse nyomon átutalásait bármikor a'
    'thank_you_for_using' = 'Köszönjük, hogy használta'
    'international_money_transfer_receipt' = 'Nemzetközi átutalás visszaigazolás'
    'fast_transparent_low_fees' = 'Gyors, Átlátható, Alacsony Díjak.'
    'we_sent_money' = 'Pénzt küldtünk a következőnek:'
    'sent_you' = 'küldött önnek'
    'business_address' = 'Üzleti Cím'
    'dont_see_money' = 'Nem látja a pénzt a számláján?'
    'dont_worry_show_up' = 'Ne aggódjon — eltarthat néhány pillanatig, amíg megjelenik.'
    'paypal_payment_received' = 'PayPal megerősítés'
    'paypal_payment_failed' = 'PayPal fizetést nem sikerült feldolgozni'
    'verify_your_identity' = 'Személyazonosságának Ellenőrzése'
    'use_code_below' = 'Használja az alábbi kódot személyazonossága ellenőrzéséhez.'
    'code_expire_10min' = 'Ez a kód 10 percen belül lejár.'
    'if_didnt_request_ignore' = 'Ha nem ön kérte ezt a kódot, kérjük, hagyja figyelmen kívül ezt az e-mailt.'
    'welcome_future_banking' = 'Üdvözöljük a Bankolás Jövőjében'
    'account_activated' = 'Számlája sikeresen aktiválásra került!'
    'instant_global_transfers' = 'Azonnali Globális Átutalások'
    'crypto_high_yield' = 'Kripto és Magas Hozamú Számlák'
    'ai_finance_insights' = 'AI Pénzügyi Elemzések'
    'dedicated_support' = '24/7 Dedikált Ügyfélszolgálat'
    'new_signin_detected' = 'Új Bejelentkezés Észlelve'
    'noticed_new_login' = 'Új bejelentkezést észleltünk számláján. Ha ez ön volt, nyugodtan hagyja figyelmen kívül ezt a riasztást.'
    'account' = 'Számla'
    'device' = 'Eszköz'
    'country' = 'Ország'
    'ip_address' = 'IP Cím'
    'if_not_you_secure' = 'Ha nem ön volt, kérjük, azonnal biztosítsa számláját.'
    'secure_my_account' = 'Számlám Biztosítása'
    'card_activity_alert' = 'Kártya Aktivitás Riasztás'
    'activity_on_card' = 'Tevékenységet észleltünk {last4} végződésű kártyáján.'
    'action_taken' = 'Intézkedés Történt'
    'manage_card_settings' = 'Kártya Beállítások Kezelése'
    'go_to_wallet' = 'Ugrás a Tárcához'
    'investment_account_activated' = 'Befektetési Számla Aktiválva'
    'congratulations_hy' = 'Gratulálunk! Mostantól többet keres Magas Hozamú Megtakarítási Számlájával.'
    'current_rate' = 'Jelenlegi Kamat'
    'initial_locked_deposit' = 'Kezdeti Zárolt Befizetés'
    'earning_more' = 'Mostantól többet keres.'
    'go_to_dashboard' = 'Ugrás a Vezérlőpulthoz'
    'order_executed' = 'Megbízás Teljesítve'
    'investment_order_filled' = 'Befektetési megbízása teljesítésre került.'
    'total_value' = 'Teljes Érték'
    'execution_price' = 'Teljesítési Árfolyam'
    'track_portfolio' = 'Kövesse nyomon portfóliója teljesítményét bármikor.'
    'view_portfolio' = 'Portfólió Megtekintése'
    'profile_updated' = 'Profil Frissítve'
    'account_changes_confirm' = 'Ez az e-mail annak megerősítésére szolgál, hogy közelmúltban változtatások történtek számlaprofiljában.'
    'update_type' = 'Frissítés Típusa'
    'contact_support' = 'Ügyfélszolgálat'
    'go_to_paypal' = 'Ugrás a PayPalra'
    'web_client' = 'Web Kliens'
    'unknown' = 'Ismeretlen'
    'action_required_unread' = 'Intézkedés Szükséges: Olvasatlan Üzenet'
    'unread_paypal_transfer' = 'olvasatlan üzenete van PayPal átutalásával kapcsolatban.'
    'review_message_confirm' = 'Kérjük, tekintse át az üzenetet és erősítse meg fizetését az átutalás folytatásához.'
    'view_message_confirm' = 'Üzenet Megtekintése és Megerősítése'
    'click_button_chat' = 'Kattintson az alábbi gombra a teljes beszélgetés megtekintéséhez és csapatunkkal való chat folytatásához.'
    'if_not_you_changes' = 'Ha nem ön végezte ezeket a változtatásokat, kérjük, azonnal lépjen kapcsolatba az ügyfélszolgálattal.'
    'manage_card_desc' = 'Kezelje kártyabeállításait bármikor a tárca vezérlőpultjáról.'
    'help_contact' = 'Segítség és Kapcsolat'
    'security' = 'Biztonság'
    'apps' = 'Alkalmazások'
    'learn_phishing' = 'Tanulja meg felismerni az adathalászatot'
    'dont_reply_email' = 'Kérjük, ne válaszoljon erre az e-mailre. Kapcsolatba lépéséhez kattintson'
    'not_sure_why' = 'Nem biztos, miért kapta ezt az e-mailt?'
    'learn_more' = 'További információ'
    'privacy' = 'Adatvédelem'
    'support' = 'Ügyfélszolgálat'
    'paypal_fraud_prevention' = 'A PayPal elkötelezett a csalárd e-mailek megelőzése mellett. A PayPal e-mailek mindig tartalmazzák teljes nevét.'
    'method' = 'Módszer'
    'view_reply_continue' = 'Válasz Megtekintése és Folytatás'
    'new_message_support' = 'Új üzenete érkezett az ügyfélszolgálattól.'
    'unread_message_from_support' = 'Olvasatlan Üzenet az Ügyfélszolgálattól'
    'welcome_to' = 'Üdvözöljük a'
    'status_success' = 'Sikeres'
    'status_pending' = 'Függőben'
    'status_failed' = 'Sikertelen'
    'status_on_hold' = 'Visszatartva'
    'status_processing' = 'Feldolgozás Alatt'
    'status_completed' = 'Teljesítve'
    'na' = 'N/A'
    'notification' = 'Értesítés'
    'customer_center' = 'Ügyfélszolgálati Központ'
    'call' = 'Hívás'
    'checking' = 'Folyószámla'
    'company_payroll' = 'Vállalati Bérlista'
    'support_team' = 'Ügyfélszolgálati Csapat'
}

# Read the file
$file = 'c:\My Projects\Web Apps\VeltrixBank-main\utils\i18n.ts'
$content = Get-Content $file -Raw -Encoding UTF8

# Update the add function signature
$content = $content -replace "function add\(k: string, en: string, es: string, fr: string, de: string, pt: string, it: string, zh: string, ja: string, ko: string, ar: string, hi: string, ru: string, tr: string, vi: string, nl: string, pl: string, id: string, th: string, sv: string, fil: string\) \{", "function add(k: string, en: string, es: string, fr: string, de: string, pt: string, it: string, zh: string, ja: string, ko: string, ar: string, hi: string, ru: string, tr: string, vi: string, nl: string, pl: string, id: string, th: string, sv: string, fil: string, hu: string) {"

# Update the DICT assignment
$content = $content -replace "DICT\[k\] = \{ en, es, fr, de, pt, it, zh, ja, ko, ar, hi, ru, tr, vi, nl, pl, id, th, sv, fil \};", "DICT[k] = { en, es, fr, de, pt, it, zh, ja, ko, ar, hi, ru, tr, vi, nl, pl, id, th, sv, fil, hu };"

# Process each add() call
$lines = $content -split "`n"
$newLines = @()

foreach ($line in $lines) {
    if ($line -match "^add\('([^']+)'") {
        $key = $matches[1]
        if ($huTranslations.ContainsKey($key)) {
            $huValue = $huTranslations[$key]
            # Add Hungarian translation at the end before the closing parenthesis
            $line = $line -replace "\);$", ", '$huValue');"
        }
    }
    $newLines += $line
}

# Write back
$newLines -join "`n" | Set-Content $file -Encoding UTF8 -NoNewline

Write-Host "Hungarian translations added successfully!"
